=== DataONEorg/d1_python/d1_workspace_client/src/d1_workspace/types/workspace_types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.0.1"
  elementFormDefault="unqualified" attributeFormDefault="unqualified">

  <xs:element name="folder" type="Folder"/>

  <xs:complexType name="Folder">
    <xs:sequence>
      <xs:element name="folder" type="Folder" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="identifier" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="query" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

</xs:schema>

=== DataONEorg/d1_python/d1_client_onedrive/src/d1_client_onedrive/impl/tests/test_workspace.xml
<?xml version="1.0" encoding="UTF-8"?>
<folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/dahl/d1/d1_python/d1_workspace_client/types/workspace_types.xsd" name="root">
  <folder name="folder_1">
    <identifier>dataone_identifier_1a</identifier>
    <identifier>dataone_identifier_1b</identifier>
    <query>solr_query_1a</query>
    <query>solr_query_1b</query>
  </folder>
  <folder name="folder_2">
    <folder name="folder_3">
      <identifier>dataone_identifier_23a</identifier>
      <identifier>dataone_identifier_23b</identifier>
      <query>solr_query_23a</query>
      <query>solr_query_23b</query>
    </folder>
    <identifier>dataone_identifier_2a</identifier>
    <identifier>dataone_identifier_2b</identifier>
    <query>solr_query_2a</query>
    <query>solr_query_2b</query>
  </folder>
  <identifier>dataone_identifier_a</identifier>
  <identifier>dataone_identifier_b</identifier>
  <query>solr_query_a</query>
  <query>solr_query_b</query>
</folder>

=== DataONEorg/d1_python/d1_client_onedrive/src/workspace_nodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/dahl/d1/d1_python/d1_workspace_client/types/workspace_types.xsd" name="root">

  <folder name="MemberNodes">
    <folder name="KNB">
      <query>datasource:urn\:node\:KNB AND -obsoletedBy:*</query>
    </folder>
    <folder name="PISCO">
      <query>datasource:urn\:node\:PISCO AND -obsoletedBy:*</query>
    </folder>
    <folder name="ESA">
      <query>datasource:urn\:node\:ESA AND -obsoletedBy:*</query>
    </folder>
    <folder name="ORNLDAAC">
      <query>datasource:urn\:node\:ORNLDAAC AND -obsoletedBy:*</query>
    </folder>
    <folder name="USGSCSAS">
      <query>datasource:urn\:node\:USGSCSAS AND -obsoletedBy:*</query>
    </folder>
    <folder name="LTER">
      <query>datasource:urn\:node\:LTER AND -obsoletedBy:*</query>
    </folder>
    <folder name="TFRI">
      <query>datasource:urn\:node\:TFRI AND -obsoletedBy:*</query>
    </folder>
  </folder>

</folder>

=== DataONEorg/d1_python/d1_client_onedrive/src/workspace.xml
<?xml version="1.0" encoding="UTF-8"?>
<folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/dahl/d1/d1_python/d1_workspace_client/types/workspace_types.xsd" name="root">

  <folder name="folder_1">
    <identifier>1860_1993_2050_NITROGEN_830.zip</identifier>
    <identifier>abligeodata.zip</identifier>
    <identifier>ACCP_CANOPYCHEM_422.zip</identifier>
    <identifier>ACCP_CANOPYSPEC_423.zip</identifier>
    <identifier>ajpelu.4.1</identifier>
    <query>id:A*</query>
    <query>id:B*</query>
  </folder>

  <folder name="folder_2">

    <folder name="folder_3">
      <identifier>Akasha.10.1</identifier>
      <identifier>Akasha.8.1</identifier>
      <identifier>AKCRRAB.31.1</identifier>
      <identifier>ark\:/13030/m50000t4/1/cadwsap-s1610004-004-main.csv</identifier>
      <identifier>alejonico.3.4</identifier>
      <query>id:C*</query>
      <query>id:D*</query>
    </folder>

    <identifier>doi\:10.5063/AA/seahoob.279.1</identifier>
    <identifier>doi\:10.5063/AA/tao.8679.1</identifier>
    <identifier>doi\:10.5063/AA/tao.8766.1</identifier>
    <identifier>doi\:10.5063/AA/test.200493113618.1</identifier>
    <query>id:E*</query>
    <query>id:F*</query>

  </folder>

  <identifier>doi\:10.6073/AA/knb-lter-mcr.32.9</identifier>
  <identifier>doi\:10.6073/AA/knb-lter-hfr.41.12</identifier>
  <identifier>doi\:10.6085/AA/LB30XX_030MXTI004R00_20050722.50.</identifier>
  <identifier>doi\:10.6085/AA/CUYXXX_015MTBD014R00_20100811.50.1</identifier>
  <identifier>resourceMap_SCPXXX_015MTBD014R00_20030612.50.4</identifier>
  <identifier>resourceMap_SH15XX_015MHP2014R00_20110412.50.1</identifier>
  <identifier>resourceMap_SH15XX_015MXTI004R00_20050420.50.6</identifier>

  <query>kingdom:['' TO *]</query>
  <query>phylum:['' TO *]</query>
  <query>class:['' TO *]</query>
  <query>order:['' TO *]</query>
  <query>family:['' TO *]</query>
  <query>genus:['' TO *]</query>
  <query>species:['' TO *]</query>
  <query>scientificName:['' TO *]</query>
  <query>author:['' TO *]</query>
  <query>site:['' TO *]</query>
  <query>beginDate:*</query>
  <query>endDate:*</query>
  <query>id:G*</query>
  <query>id:H*</query>
</folder>

=== DataONEorg/d1_python/client_workspace/src/d1_workspace/tests/workspace_single.xml
<?xml version="1.0" encoding="UTF-8"?>
<folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/dahl/d1/d1_python/d1_workspace_client/types/workspace_types.xsd" name="root">

  <folder name="single">
    <identifier>Akasha.10.1</identifier>
    <identifier>Akasha.8.1</identifier>
    <identifier>AKCRRAB.31.1</identifier>
    <identifier>ark\:/13030/m50000t4/1/cadwsap-s1610004-004-main.csv</identifier>
    <identifier>alejonico.3.4</identifier>
    <query>id:C*</query>
    <query>id:D*</query>
  </folder>

</folder>

=== DataONEorg/d1_python/client_onedrive/src/workspace_taxa.xml
<?xml version="1.0" encoding="UTF-8"?>
<folder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/dahl/d1/d1_python/d1_workspace_client/types/workspace_types.xsd" name="root">
  <query>kingdom:['' TO *] AND -obsoletedBy:*</query>
  <query>phylum:['' TO *] AND -obsoletedBy:*</query>
  <query>class:['' TO *] AND -obsoletedBy:*</query>
  <query>order:['' TO *] AND -obsoletedBy:*</query>
  <query>family:['' TO *] AND -obsoletedBy:*</query>
  <query>genus:['' TO *] AND -obsoletedBy:*</query>
  <query>species:['' TO *] AND -obsoletedBy:*</query>
  <query>scientificName:['' TO *] AND -obsoletedBy:*</query>
  <query>author:['' TO *] AND -obsoletedBy:*</query>
  <query>site:['' TO *] AND -obsoletedBy:*</query>
  <query>beginDate:* AND -obsoletedBy:*</query>
  <query>endDate:* AND -obsoletedBy:*</query>
</folder>
